# Generated by Django 5.1.2 on 2024-11-01 07:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
    ]

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(max_length=60, unique=True, verbose_name="email"),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="username"
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=60, null=True, verbose_name="full name"
                    ),
                ),
                (
                    "ssn",
                    models.CharField(
                        max_length=9, null=True, unique=True, verbose_name="ssn"
                    ),
                ),
                (
                    "user_role",
                    models.CharField(
                        choices=[
                            ("ownr", "Owner"),
                            ("mngr", "Manager"),
                            ("oper", "Operator"),
                        ],
                        default="oper",
                        max_length=4,
                    ),
                ),
                ("is_admin", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Location",
            fields=[
                ("location_id", models.AutoField(primary_key=True, serialize=False)),
                ("lat", models.FloatField()),
                ("lng", models.FloatField()),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "location_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Bookmark",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routeManager.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Log",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("crt", "Created"),
                            ("upd", "Updated"),
                            ("del", "Deleted"),
                            ("lgn", "Logged In"),
                            ("lgt", "Logged Out"),
                            ("non", "None"),
                        ],
                        default="non",
                        max_length=3,
                    ),
                ),
                ("object_id", models.PositiveIntegerField(null=True)),
                ("field_name", models.CharField(max_length=255, null=True)),
                ("old_value", models.TextField(null=True)),
                ("new_value", models.TextField(null=True)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Note",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="routeManager.location",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Plan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("plan_name", models.CharField(blank=True, max_length=255, null=True)),
                ("est_distance", models.FloatField(blank=True, null=True)),
                ("est_duration", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pendng", "Pending"),
                            ("accept", "Accepted"),
                            ("reject", "Rejected"),
                            ("cancel", "Canceled"),
                            ("progrs", "In-progress"),
                            ("complt", "Complete"),
                        ],
                        default="pendng",
                        max_length=6,
                    ),
                ),
                ("route_data", models.JSONField(blank=True, null=True)),
                (
                    "clearance",
                    models.CharField(
                        choices=[("cfdt", "Is confidential"), ("open", "Is open")],
                        default="open",
                        max_length=4,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
